/**
 * The `ai` binding's test-environment behaviour, pinned.
 *
 * Decision log 37 recorded, as the blocking open problem for section 21's
 * Assess stage, that declaring `{"ai": {"binding": "AI"}}` in wrangler.jsonc's
 * testnet environment broke the ENTIRE suite: Workers AI has no local
 * simulation, so `@cloudflare/vitest-pool-workers` opened a remote proxy session
 * to the real account at config-parse time, which this project's Cloudflare
 * Access policy refuses, and the run reported 0 tests with an error per file.
 *
 * It is resolved by ONE option in `vitest.config.ts`: `remoteBindings: false`.
 * The pool starts the session only `if (options.remoteBindings)`, and that flag
 * defaults to TRUE, so the failure was the default rather than anything this
 * project configured. See the comment on that option for the full reasoning.
 *
 * This file exists because the resolution is a CONFIGURATION fact, and a
 * configuration fact with no test is one edit away from silently reverting. Two
 * properties, and the second matters more than the first:
 *
 *  1. THE BINDING EXISTS IN TESTS. If `env.AI` were absent, the wrangler config
 *     would have lost the binding -- and a deploy would then ship a Worker whose
 *     `env.AI` is undefined, which no test would otherwise notice.
 *  2. CALLING IT FAILS, LOCALLY AND LOUDLY. `remoteBindings: false` leaves the
 *     binding wired to a proxy client with no connection string, so any use
 *     throws `Binding AI needs to be run remotely` BEFORE issuing any request.
 *     That is the desired behaviour and not a limitation: **no test in this
 *     repository may ever reach a real model**, and `AssessModel`
 *     (`src/research/assess.ts`) is an injected port precisely so nothing has to
 *     rely on this failure. A test that somehow did call `env.AI` should fail
 *     loudly rather than quietly spend money against a paid API.
 *
 * If someone later flips `remoteBindings` back to true, property 2's assertion
 * is what tells them why the suite suddenly cannot start -- here, with the
 * reasoning attached, rather than in a stack trace from the pool.
 */

import { env } from "cloudflare:test";
import { describe, expect, it } from "vitest";

/**
 * `Env` does not declare `AI`: `worker-configuration.d.ts` is generated by
 * `wrangler types` and has not been regenerated since the binding was added.
 * Narrowed locally rather than regenerating 550KB of types for a test -- and
 * the regeneration is a real follow-up, noted in the decision log, for whenever
 * production code first needs `env.AI` to typecheck.
 */
const aiBinding = (env as unknown as { AI?: { run: (...args: unknown[]) => Promise<unknown> } }).AI;

describe("the Workers AI binding in tests", () => {
  it("exists, so a lost wrangler declaration is caught here rather than at deploy", () => {
    expect(aiBinding).toBeDefined();
  });

  it("cannot reach Cloudflare: calling it throws locally instead of making a request", async () => {
    expect(aiBinding).toBeDefined();

    // No `remoteProxyConnectionString` is bound, so miniflare's proxy client
    // throws on property access / invocation rather than issuing a fetch. This
    // assertion is the guarantee that the suite spends no money and contacts no
    // model, stated as a test rather than as a comment.
    await expect(
      (async () => await aiBinding!.run("@cf/meta/llama-3.3-70b-instruct-fp8-fast", { prompt: "x" }))(),
    ).rejects.toThrow(/needs to be run remotely/);
  });
});
